### ISSUE TITLE
n-1 Dummies

### ISSUE THREAD

**Issue by benjaminschlegel** [jacobkap/fastDummies#1]
Thanks a lot for the great package, it's very usefull.

Is there a possibility you could add an option that removes the first dummy of every variable that only n-1 Dummies remain? It would be very helpfull for models which need numeric data, but only n-1 Dummies because of perfect multicolinearity.

The code for it:
- add variable "remove.first.dummy = FALSE" as parameter to the function (or however you want to call it)
- add the code below:

  for (col_name in char_cols) {
    unique_vals <- unique(dataset[, get(col_name)])
#----- next lines new ---
    if(remove.first.dummy){
      unique_vals = unique_vals[-1]
    }
#-------------------------
    dataset[, (paste0(col_name, "_", unique_vals)) := 0]
    for (unique_values in unique_vals) {
      dataset[get(col_name) == unique_values,
              (paste0(col_name, "_", unique_values)) := 1]
    }
  }

**Comment by jacobkap** [comment]
Thanks for your contribution! I'll update the package soon. Would you like to be added as a contributor to the package?

**Comment by benjaminschlegel** [comment]
If it's not much work for you to add me, that would be nice.

**Comment by jacobkap** [comment]
Can you send me your email? I can add that to the documentation.

**Comment by benjaminschlegel** [comment]
kontakt@benjaminschlegl.ch
