### ISSUE TITLE
Dummy indicator with more than one endorsement

### ISSUE THREAD

**Issue by mattsigal** [jacobkap/fastDummies#10]
I just came across your package and it looks very close to what I need. If you are still maintaining this package, an additional feature that would be extremely handy would be to allow for multiple categories to be selected (using a delimiter).

For example, I am working with a variable "Type" and some rows might be "Research", "Teaching", "Unknown", but others might be a combination: "Research, Teaching". When "dummied", I am looking for something that might look like:

Research | Teaching | Unknown
0 | 0 | 1
1 | 1 | 0

Being able to specify the delimiter (in this case, the comma followed by a space) would be a huge help.

Any ideas if this might be possible?

**Comment by jacobkap** [comment]
Hi Matthew,

Thanks for the suggestion. I'll give it some thought.

Best,
Jacob

**Comment by jacobkap** [comment]
I'm not sure how to do this well. If you have code that does this can you submit a pull request?

**Comment by jacobkap** [comment]
Hi Matthew, 

Please check out the current dev version of this package which now has this feature.
