### ISSUE TITLE
Sort dummy columns following factor order.

### ISSUE THREAD

**Issue by pbaylis** [jacobkap/fastDummies#11]
It would be useful for me to have the dummy columns this package creates (optionally) follow the ordering of the original factor variables. Maybe also true for others. For example, this [issue](https://github.com/jacobkap/fastDummies/issues/9) could be resolved as well. I wrote some code to do this, happy to submit a PR if that's something you're willing to add.

**Comment by jacobkap** [comment]
Yes, please submit a pull request.
