### ISSUE TITLE
dummy_cols creates dummies for missing values

### ISSUE THREAD

**Issue by juribep5** [jacobkap/fastDummies#13]
Hi,

I was using dummy_cols and the function is creating values for the missing values. Then I have more data for the new columns than the original data.

Is there any solution to avoid creating values for the Na?

Thanks

**Comment by jacobkap** [comment]
Hi,

Thanks for the comment. To confirm what you mean, is this correct?

test <- data.frame(animal = c("cat", NA, "dog")

then dummy_cols makes it
animal   animal_cat   animal_NA  animal_dog
cat         1                  0                  0
NA         0                  1                  0
dog        0                  0                  1

I can add a parameter to ignore_na.

**Comment by juribep5** [comment]
Yes!! Exactly like that!!

Amazing that you can add the parameter, because it can distort a lot the results.

Thanks!!

**Comment by jacobkap** [comment]
Can you check the dev version to see if it's right?
