### ISSUE TITLE
Can we create dummies from multiple character values

### ISSUE THREAD

**Issue by ANDEF89** [jacobkap/fastDummies#14]
suppose we have a data frame
fastDummies_example <- data.frame(owner = 1:4,
                               Pets = c("dog", "dog, cat, hamster", "cat", 
                                        "hamster"), stringsAsFactors = FALSE)

owner 2 has multiple Pets, so could we assign dummies with respect to those multiple strings
so we should have 
owner              Pets                        Pets_dog P    Pets_cat   Pets_hamster
     1                 dog                               1                    0              0
     2                 dog, cat, hamster          1                    1              1
     3                 cat                                  0                    1              0
     4                 hamster                          0                    0              1

**Comment by jacobkap** [comment]
This feature has been added as the split parameter.

**Comment by ANDEF89** [comment]
>Thanks for the update. i was wondering if we need the column with the multiple strings since individual dummy columns are created e. g column name "Pets_dog, cat, hamster" needed or can it be dropped ?
