### ISSUE TITLE
Feature Request: Code NA as NA

### ISSUE THREAD

**Issue by DLustenberger** [jacobkap/fastDummies#18]
Setting the ignore_na argument to "TRUE" appears to set the value for all dummy codes to 0. It'd be helpful to have an additional option to code NA values appearing in the source column as NA in all corresponding dummy columns. (This would be consistent with psych::dummy.code().) In many cases, if I don't know what the original value was, I don't want to make assumptions about what that value is in the corresponding dummy columns.

**Comment by jacobkap** [comment]
Good idea, thanks. I'll work on this over the weekend.
