### ISSUE TITLE
Error in setalloccol(ans) : can't set ALTREP truelength

### ISSUE THREAD

**Issue by annacheyette** [jacobkap/fastDummies#20]
Hello,

I have been trying to re-compile some old code that I created on R 3.6.2, but have since started using R 4.0.2. Much of the code uses `dummy_cols()`, which has worked well in the past, but now I get the error `Error in setalloccol(ans) : can't set ALTREP truelength` when performing a standard `dummy_cols()` operation. I've spoken to other people at my organization who are experiencing the same issue. I've tried reverting to R 3.6, un-installing and re-installing `fastDummies`, to no avail. 

An update to fix this would be very much appreciated. Thanks!

**Comment by jacobkap** [comment]
Hi @annacheyette, can you please include a reproducible example of the issue?
