### ISSUE TITLE
dummy_cols alters the input dataset

### ISSUE THREAD

**Issue by ArmandoRl1** [jacobkap/fastDummies#24]
When doing the following
```
dummy_df <- dummy_cols(df, remove_first_dummy = T, remove_selected_columns = T)
```
df gets altered too, containing all the dummy variables. It should not be modified, saving the results only in the return value (dummy_df).

**Comment by jacobkap** [comment]
Please submit a reproducible example. https://stackoverflow.com/help/minimal-reproducible-example
