### ISSUE TITLE
ignore_na not working as intended

### ISSUE THREAD

**Issue by mysakbm** [jacobkap/fastDummies#29]
I have NAs in dataset and when using function dummy_col(), with the ignore_na = F as default it will create new column with _NA, however, it will leave all NAs in the original dataset. Per help, however, it should replace the NA values.

**Comment by jacobkap** [comment]
Hi, please submit a reproducible example. https://gist.github.com/hadley/270442

**Comment by mysakbm** [comment]
I dont think that you need a reproducible example. It's self-explanatory. 
However, 
```
df = data.frame(colname = c(NaN, 1, 2)
df %>% dummy_cols(ignore_na = TRUE)
```

parameter 'ignore_cols' has no effect on the outcome. 
Using RStudio: 2023.06.0, build 421, 
R version: 4.2.2
FastDummies package version: 1.6.3

**Comment by jacobkap** [comment]
NaN and NA are not the same and are not treated the same in R. https://stackoverflow.com/questions/15496361/what-is-the-difference-between-nan-and-inf-and-null-and-na-in-r

This is why it is important to provide a reproducible example.
