### ISSUE TITLE
Use dummy_cols to add columns by reference to data.table 

### ISSUE THREAD

**Issue by ChandlerLutz** [jacobkap/fastDummies#4]
Sorry for submitting multiple issues, but I hope that this makes it easier to address and track them. 

Looking at the code for `dummy_cols()`, it seems that the function uses `data.table::set()` to add the dummy columns. data.table users with larger datasets may be interested in adding these columns by reference instead of copying the dataset. It looks like the function could accommodate this rather easily, but it may confuse new users if this is implemented in the original `dummy_cols` function. I'm not sure the best way to address this, but maybe a second function would be the right approach.

**Comment by jacobkap** [comment]
Hi Chandler,

Thanks for all your suggestions! I will look into this.
